ExUnit.start()
Code.require_file("support/snapshot_support.exs", __DIR__)
Code.require_file("support/test_support.exs", __DIR__)
Code.require_file("support/auth_oidc_fixture.exs", __DIR__)
Code.require_file("support/auth_db_fixture.exs", __DIR__)
